version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017

  frontend:
    image: ghcr.io/spe-uob/2023-CityFarm-frontend:dev
    ports:
      - 3000:3000

  backend:
    image: ghcr.io/spe-uob/2023-CityFarm-backend:dev
    ports:
      - 8080:8080
