volumes:
  mongodb-data:

services:
  mongodb:
    container_name: cityfarm-mongodb
    image: ghcr.io/spe-uob/2023-cityfarm/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db:rw
    pull_policy: always
  
  backend:
    container_name: cityfarm-backend
    image: ghcr.io/spe-uob/2023-cityfarm/backend:dev
    ports:
      - 8918:8080
    pull_policy: always

  frontend:
    container_name: cityfarm-frontend
    image: ghcr.io/spe-uob/2023-cityfarm/frontend:dev
    ports:
      - 8919:3000
    pull_policy: always